(ns slopp.ui.wire.api
  "Endpoint descriptors for an API this app CONSUMES — generated by
  generate_client, one per endpoint, from the SAME contract the
  server publishes.

  Turn one into a request with slopp.http.endpoint/request and drop
  that into a route row's :request; slopp addresses it under the
  app's mount point and performs it. Each descriptor carries its own
  :rest/response, so the answer is checked against the contract the
  producer published without a second var to keep in step.

  Regenerate, never hand-edit: every form here is ^:generated and the
  next generate_client overwrites the namespace wholesale."
  (:require
            slopp.ui.wire.contracts))

(def ^{:generated "form" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export form
  "GET /api/form/:id — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/form/:id"
   :http/params   #{:depth :id :view}
   :rest/request  slopp.ui.wire.contracts/form-request
   :rest/response slopp.ui.wire.contracts/form-response})

(def ^{:generated "timeline" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export timeline
  "GET /api/timeline — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/timeline"
   :rest/response slopp.ui.wire.contracts/timeline-response})

(def ^{:generated "cost" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export cost
  "GET /api/cost — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/cost"
   :http/params   #{:by}
   :rest/request  slopp.ui.wire.contracts/cost-request
   :rest/response slopp.ui.wire.contracts/cost-response})

(def ^{:generated "change" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export change
  "GET /api/change/:range — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/change/:range"
   :http/params   #{:range}
   :rest/request  slopp.ui.wire.contracts/change-request
   :rest/response slopp.ui.wire.contracts/change-response})

(def ^{:generated "webapp-paths" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export webapp-paths
  "GET /api/webapp/paths — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/webapp/paths"
   :rest/response slopp.ui.wire.contracts/webapp-paths-response})

(def ^{:generated "http-paths" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export http-paths
  "GET /api/http/paths — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/http/paths"
   :rest/response slopp.ui.wire.contracts/http-paths-response})

(def ^{:generated "namespaces" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export namespaces
  "GET /api/namespaces — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/namespaces"
   :rest/response slopp.ui.wire.contracts/namespaces-response})

(def ^{:generated "rest-paths" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export rest-paths
  "GET /api/rest/paths — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/rest/paths"
   :rest/response slopp.ui.wire.contracts/rest-paths-response})

(def ^{:generated "config" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export config
  "GET /api/config — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/config"
   :http/params   #{:prefix}
   :rest/request  slopp.ui.wire.contracts/config-request
   :rest/response slopp.ui.wire.contracts/config-response})

(def ^{:generated "modules" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export modules
  "GET /api/modules — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/modules"
   :rest/response slopp.ui.wire.contracts/modules-response})

(def ^{:generated "bundle" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export bundle
  "GET /api/bundle — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/bundle"
   :rest/response slopp.ui.wire.contracts/bundle-response})

(def ^{:generated "source" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export source
  "GET /api/source/:ns/:name — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/source/:ns/:name"
   :http/params   #{:name :ns}
   :rest/request  slopp.ui.wire.contracts/source-request
   :rest/response slopp.ui.wire.contracts/source-response})

(def ^{:generated "search" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export search
  "GET /api/search — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/search"
   :http/params   #{:limit :q}
   :rest/request  slopp.ui.wire.contracts/search-request
   :rest/response slopp.ui.wire.contracts/search-response})

(def ^{:generated "module" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export module
  "GET /api/module/:m — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/module/:m"
   :http/params   #{:m}
   :rest/request  slopp.ui.wire.contracts/module-request
   :rest/response slopp.ui.wire.contracts/module-response})

(def ^{:generated "ns-outline" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export ns-outline
  "GET /api/ns/:ns — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/ns/:ns"
   :http/params   #{:ns}
   :rest/request  slopp.ui.wire.contracts/ns-outline-request
   :rest/response slopp.ui.wire.contracts/ns-outline-response})

(def ^{:generated "otel-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export otel-endpoint
  "POST /api/otel/v1/logs — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/otel/v1/logs"
   :http/params   #{:resourceLogs}
   :rest/request  slopp.ui.wire.contracts/otel-endpoint-request
   :rest/response slopp.ui.wire.contracts/otel-endpoint-response})

(def ^{:generated "status-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export status-endpoint
  "GET /api/status — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/status"
   :rest/response slopp.ui.wire.contracts/status-endpoint-response})

(def ^{:generated "mcp-delete-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export mcp-delete-endpoint
  "DELETE /api/projects/:slug/mcp — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :delete
   :http/path     "/api/projects/:slug/mcp"
   :http/params   #{:slug}
   :rest/response slopp.ui.wire.contracts/mcp-delete-endpoint-response})

(def ^{:generated "projects-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export projects-endpoint
  "GET /api/projects — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects"
   :rest/response slopp.ui.wire.contracts/projects-endpoint-response})

(def ^{:generated "mcp-post-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export mcp-post-endpoint
  "POST /api/projects/:slug/mcp — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/projects/:slug/mcp"
   :http/params   #{:error :id :jsonrpc :method :params :result :slug}
   :rest/request  slopp.ui.wire.contracts/mcp-post-endpoint-request
   :rest/response slopp.ui.wire.contracts/mcp-post-endpoint-response})

(def ^{:generated "mcp-get-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export mcp-get-endpoint
  "GET /api/projects/:slug/mcp — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/mcp"
   :http/params   #{:slug}
   :rest/response slopp.ui.wire.contracts/mcp-get-endpoint-response})

(def ^{:generated "project-api-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export project-api-endpoint
  "GET /api/projects/:slug/** — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/**"
   :http/params   #{:* :slug}
   :rest/response slopp.ui.wire.contracts/project-api-endpoint-response})

(def ^{:generated "call-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7357/api/projects/slopp2/rest/paths"} ^:export call-endpoint
  "POST /api/projects/:slug/call — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/projects/:slug/call"
   :http/params   #{:agent :arguments :slug :token :tool}
   :rest/request  slopp.ui.wire.contracts/call-endpoint-request
   :rest/response slopp.ui.wire.contracts/call-endpoint-response})
