(ns slopp-server.ui.wire.api
  "Endpoint descriptors for an API this app CONSUMES — generated by
  generate_client, one per endpoint, from the SAME contract the
  server publishes.

  Turn one into a request with slopp.http.endpoint/request and drop
  that into a route row's :request; slopp addresses it under the
  app's mount point and performs it. Each descriptor carries its own
  :rest/response, so the answer is checked against the contract the
  producer published without a second var to keep in step.

  Regenerate, never hand-edit: every form here is ^:generated and the
  next generate_client overwrites the namespace wholesale."
  (:require
            slopp-server.ui.wire.contracts))

(def ^{:generated "form" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export form
  "GET /api/projects/:slug/form/:id — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/form/:id"
   :http/params   #{:depth :id :slug :view}
   :rest/request  slopp-server.ui.wire.contracts/form-request
   :rest/response slopp-server.ui.wire.contracts/form-response})

(def ^{:generated "timeline" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export timeline
  "GET /api/projects/:slug/timeline — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/timeline"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/timeline-response})

(def ^{:generated "cost" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export cost
  "GET /api/projects/:slug/cost — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/cost"
   :http/params   #{:by :slug}
   :rest/request  slopp-server.ui.wire.contracts/cost-request
   :rest/response slopp-server.ui.wire.contracts/cost-response})

(def ^{:generated "change" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export change
  "GET /api/projects/:slug/change/:range — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/change/:range"
   :http/params   #{:range :slug}
   :rest/request  slopp-server.ui.wire.contracts/change-request
   :rest/response slopp-server.ui.wire.contracts/change-response})

(def ^{:generated "webapp-paths" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export webapp-paths
  "GET /api/projects/:slug/webapp/paths — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/webapp/paths"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/webapp-paths-response})

(def ^{:generated "http-paths" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export http-paths
  "GET /api/projects/:slug/http/paths — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/http/paths"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/http-paths-response})

(def ^{:generated "namespaces" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export namespaces
  "GET /api/projects/:slug/namespaces — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/namespaces"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/namespaces-response})

(def ^{:generated "rest-paths" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export rest-paths
  "GET /api/projects/:slug/rest/paths — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/rest/paths"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/rest-paths-response})

(def ^{:generated "config" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export config
  "GET /api/projects/:slug/config — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/config"
   :http/params   #{:prefix :slug}
   :rest/request  slopp-server.ui.wire.contracts/config-request
   :rest/response slopp-server.ui.wire.contracts/config-response})

(def ^{:generated "modules" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export modules
  "GET /api/projects/:slug/modules — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/modules"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/modules-response})

(def ^{:generated "bundle" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export bundle
  "GET /api/projects/:slug/bundle — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/bundle"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/bundle-response})

(def ^{:generated "source" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export source
  "GET /api/projects/:slug/source/:ns/:name — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/source/:ns/:name"
   :http/params   #{:name :ns :slug}
   :rest/request  slopp-server.ui.wire.contracts/source-request
   :rest/response slopp-server.ui.wire.contracts/source-response})

(def ^{:generated "search" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export search
  "GET /api/projects/:slug/search — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/search"
   :http/params   #{:limit :q :slug}
   :rest/request  slopp-server.ui.wire.contracts/search-request
   :rest/response slopp-server.ui.wire.contracts/search-response})

(def ^{:generated "module" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export module
  "GET /api/projects/:slug/module/:m — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/module/:m"
   :http/params   #{:m :slug}
   :rest/request  slopp-server.ui.wire.contracts/module-request
   :rest/response slopp-server.ui.wire.contracts/module-response})

(def ^{:generated "ns-outline" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export ns-outline
  "GET /api/projects/:slug/ns/:ns — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/ns/:ns"
   :http/params   #{:ns :slug}
   :rest/request  slopp-server.ui.wire.contracts/ns-outline-request
   :rest/response slopp-server.ui.wire.contracts/ns-outline-response})

(def ^{:generated "otel-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export otel-endpoint
  "POST /api/otel/v1/logs — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/otel/v1/logs"
   :http/params   #{:resourceLogs}
   :rest/request  slopp-server.ui.wire.contracts/otel-endpoint-request
   :rest/response slopp-server.ui.wire.contracts/otel-endpoint-response})

(def ^{:generated "status-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export status-endpoint
  "GET /api/status — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/status"
   :rest/response slopp-server.ui.wire.contracts/status-endpoint-response})

(def ^{:generated "mcp-delete-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export mcp-delete-endpoint
  "DELETE /api/mcp — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :delete
   :http/path     "/api/mcp"
   :rest/response slopp-server.ui.wire.contracts/mcp-delete-endpoint-response})

(def ^{:generated "projects-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export projects-endpoint
  "GET /api/projects — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects"
   :rest/response slopp-server.ui.wire.contracts/projects-endpoint-response})

(def ^{:generated "hook-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export hook-endpoint
  "POST /api/hook — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/hook"
   :http/params   #{:hook}
   :rest/request  slopp-server.ui.wire.contracts/hook-endpoint-request
   :rest/response slopp-server.ui.wire.contracts/hook-endpoint-response})

(def ^{:generated "mcp-post-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export mcp-post-endpoint
  "POST /api/mcp — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/mcp"
   :http/params   #{:error :id :jsonrpc :method :params :result}
   :rest/request  slopp-server.ui.wire.contracts/mcp-post-endpoint-request
   :rest/response slopp-server.ui.wire.contracts/mcp-post-endpoint-response})

(def ^{:generated "cli-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export cli-endpoint
  "POST /api/cli — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/cli"
   :rest/request  slopp-server.ui.wire.contracts/cli-endpoint-request
   :rest/response slopp-server.ui.wire.contracts/cli-endpoint-response})

(def ^{:generated "mcp-get-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export mcp-get-endpoint
  "GET /api/mcp — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/mcp"
   :rest/response slopp-server.ui.wire.contracts/mcp-get-endpoint-response})

(def ^{:generated "call-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export call-endpoint
  "POST /api/call — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/call"
   :http/params   #{:agent :arguments :token :tool}
   :rest/request  slopp-server.ui.wire.contracts/call-endpoint-request
   :rest/response slopp-server.ui.wire.contracts/call-endpoint-response})
