(ns slopp-server.ui.wire.api
  "Endpoint descriptors for an API this app CONSUMES — generated by
  generate_client, one per endpoint, from the SAME contract the
  server publishes.

  Turn one into a request with slopp.http.endpoint/request and drop
  that into a route row's :request; slopp addresses it under the
  app's mount point and performs it. Each descriptor carries its own
  :rest/response, so the answer is checked against the contract the
  producer published without a second var to keep in step.

  Regenerate, never hand-edit: every form here is ^:generated and the
  next generate_client overwrites the namespace wholesale.

  HAND-OWNED since 2026-09-23, and why. The slopp server now publishes its
  read API at server-mounted paths (`/api/projects/:slug/...`) while this app
  addresses a project by prefixing project-relative descriptors
  (`slopp-server.ui.views/at-project`). A regeneration against the current
  contract changed every descriptor's shape and broke every screen; the
  descriptors here are the project-relative ones the app is written against.
  Regenerate only together with a change to `at-project` that fills `:slug`
  instead of prefixing."
  (:require
            slopp-server.ui.wire.contracts))

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export form
  "GET /api/form/:id — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/form/:id"
   :http/params   #{:depth :id :view}
   :rest/request  slopp-server.ui.wire.contracts/form-request
   :rest/response slopp-server.ui.wire.contracts/form-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export timeline
  "GET /api/timeline — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/timeline"
   :rest/response slopp-server.ui.wire.contracts/timeline-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export cost
  "GET /api/cost — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/cost"
   :http/params   #{:by}
   :rest/request  slopp-server.ui.wire.contracts/cost-request
   :rest/response slopp-server.ui.wire.contracts/cost-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export change
  "GET /api/change/:range — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/change/:range"
   :http/params   #{:range}
   :rest/request  slopp-server.ui.wire.contracts/change-request
   :rest/response slopp-server.ui.wire.contracts/change-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export webapp-paths
  "GET /api/webapp/paths — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/webapp/paths"
   :rest/response slopp-server.ui.wire.contracts/webapp-paths-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export http-paths
  "GET /api/http/paths — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/http/paths"
   :rest/response slopp-server.ui.wire.contracts/http-paths-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export namespaces
  "GET /api/namespaces — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/namespaces"
   :rest/response slopp-server.ui.wire.contracts/namespaces-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export rest-paths
  "GET /api/rest/paths — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/rest/paths"
   :rest/response slopp-server.ui.wire.contracts/rest-paths-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export config
  "GET /api/config — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/config"
   :http/params   #{:prefix}
   :rest/request  slopp-server.ui.wire.contracts/config-request
   :rest/response slopp-server.ui.wire.contracts/config-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export modules
  "GET /api/modules — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/modules"
   :rest/response slopp-server.ui.wire.contracts/modules-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export bundle
  "GET /api/bundle — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/bundle"
   :rest/response slopp-server.ui.wire.contracts/bundle-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export source
  "GET /api/source/:ns/:name — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/source/:ns/:name"
   :http/params   #{:name :ns}
   :rest/request  slopp-server.ui.wire.contracts/source-request
   :rest/response slopp-server.ui.wire.contracts/source-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export search
  "GET /api/search — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/search"
   :http/params   #{:limit :q}
   :rest/request  slopp-server.ui.wire.contracts/search-request
   :rest/response slopp-server.ui.wire.contracts/search-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export module
  "GET /api/module/:m — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/module/:m"
   :http/params   #{:m}
   :rest/request  slopp-server.ui.wire.contracts/module-request
   :rest/response slopp-server.ui.wire.contracts/module-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export ns-outline
  "GET /api/ns/:ns — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/ns/:ns"
   :http/params   #{:ns}
   :rest/request  slopp-server.ui.wire.contracts/ns-outline-request
   :rest/response slopp-server.ui.wire.contracts/ns-outline-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export otel-endpoint
  "POST /api/otel/v1/logs — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/otel/v1/logs"
   :http/params   #{:resourceLogs}
   :rest/request  slopp-server.ui.wire.contracts/otel-endpoint-request
   :rest/response slopp-server.ui.wire.contracts/otel-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export status-endpoint
  "GET /api/status — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/status"
   :rest/response slopp-server.ui.wire.contracts/status-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export mcp-delete-endpoint
  "DELETE /api/projects/:slug/mcp — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :delete
   :http/path     "/api/projects/:slug/mcp"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/mcp-delete-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export projects-endpoint
  "GET /api/projects — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects"
   :rest/response slopp-server.ui.wire.contracts/projects-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export mcp-post-endpoint
  "POST /api/projects/:slug/mcp — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/projects/:slug/mcp"
   :http/params   #{:error :id :jsonrpc :method :params :result :slug}
   :rest/request  slopp-server.ui.wire.contracts/mcp-post-endpoint-request
   :rest/response slopp-server.ui.wire.contracts/mcp-post-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export mcp-get-endpoint
  "GET /api/projects/:slug/mcp — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/mcp"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/mcp-get-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export call-endpoint
  "POST /api/projects/:slug/call — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/projects/:slug/call"
   :http/params   #{:agent :arguments :slug :token :tool}
   :rest/request  slopp-server.ui.wire.contracts/call-endpoint-request
   :rest/response slopp-server.ui.wire.contracts/call-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export project-api-endpoint
  "GET /api/projects/:slug/** — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/**"
   :http/params   #{:* :slug}
   :rest/response slopp-server.ui.wire.contracts/project-api-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export story
  "GET /api/story/:grain/:subject — a namespace's or a module's history, told by commit point."
  {:http/method   :get
   :http/path     "/api/story/:grain/:subject"
   :http/params   #{:grain :subject :page}
   :rest/request  slopp-server.ui.wire.contracts/story-request
   :rest/response slopp-server.ui.wire.contracts/story-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export entries
  "GET /api/entries — every door into the store, by kind."
  {:http/method   :get
   :http/path     "/api/entries"
   :rest/response slopp-server.ui.wire.contracts/entries-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export form-sequence
  "GET /api/form/:id/sequence — what happens when one form runs, as the code writes it."
  {:http/method   :get
   :http/path     "/api/form/:id/sequence"
   :http/params   #{:id :depth :steps}
   :rest/request  slopp-server.ui.wire.contracts/sequence-request
   :rest/response slopp-server.ui.wire.contracts/sequence-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export flow
  "GET /api/flow — the call path between two forms, drawn as a sequence."
  {:http/method   :get
   :http/path     "/api/flow"
   :http/params   #{:from :to}
   :rest/request  slopp-server.ui.wire.contracts/flow-request
   :rest/response slopp-server.ui.wire.contracts/sequence-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export overlay
  "GET /api/overlay/:dial — what one dial tints the Code map by."
  {:http/method   :get
   :http/path     "/api/overlay/:dial"
   :http/params   #{:dial}
   :rest/request  slopp-server.ui.wire.contracts/overlay-request
   :rest/response slopp-server.ui.wire.contracts/overlay-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export data
  "GET /api/data — the data dictionary, and with ?key= one key's users."
  {:http/method   :get
   :http/path     "/api/data"
   :http/params   #{:q :bare :key :limit}
   :rest/request  slopp-server.ui.wire.contracts/data-request
   :rest/response slopp-server.ui.wire.contracts/data-response})
