(ns slopp-server.ui.wire.api
  "Endpoint descriptors for an API this app CONSUMES — generated by
  generate_client, one per endpoint, from the SAME contract the
  server publishes.

  Turn one into a request with slopp.http.endpoint/request and drop
  that into a route row's :request; slopp addresses it under the
  app's mount point and performs it. Each descriptor carries its own
  :rest/response, so the answer is checked against the contract the
  producer published without a second var to keep in step.

  Regenerate, never hand-edit: every form here is ^:generated and the
  next generate_client overwrites the namespace wholesale."
  (:require
            slopp-server.ui.wire.contracts))

(def ^{:generated "form" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export form
  "GET /api/projects/:slug/form/:id — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/form/:id"
   :http/params   #{:depth :id :slug :view}
   :rest/request  slopp-server.ui.wire.contracts/form-request
   :rest/response slopp-server.ui.wire.contracts/form-response})

(def ^{:generated "timeline" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export timeline
  "GET /api/projects/:slug/timeline — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/timeline"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/timeline-response})

(def ^{:generated "cost" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export cost
  "GET /api/projects/:slug/cost — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/cost"
   :http/params   #{:by :slug}
   :rest/request  slopp-server.ui.wire.contracts/cost-request
   :rest/response slopp-server.ui.wire.contracts/cost-response})

(def ^{:generated "change" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export change
  "GET /api/projects/:slug/change/:range — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/change/:range"
   :http/params   #{:range :slug}
   :rest/request  slopp-server.ui.wire.contracts/change-request
   :rest/response slopp-server.ui.wire.contracts/change-response})

(def ^{:generated "webapp-paths" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export webapp-paths
  "GET /api/projects/:slug/webapp/paths — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/webapp/paths"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/webapp-paths-response})

(def ^{:generated "http-paths" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export http-paths
  "GET /api/projects/:slug/http/paths — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/http/paths"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/http-paths-response})

(def ^{:generated "namespaces" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export namespaces
  "GET /api/projects/:slug/namespaces — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/namespaces"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/namespaces-response})

(def ^{:generated "rest-paths" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export rest-paths
  "GET /api/projects/:slug/rest/paths — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/rest/paths"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/rest-paths-response})

(def ^{:generated "config" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export config
  "GET /api/projects/:slug/config — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/config"
   :http/params   #{:prefix :slug}
   :rest/request  slopp-server.ui.wire.contracts/config-request
   :rest/response slopp-server.ui.wire.contracts/config-response})

(def ^{:generated "modules" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export modules
  "GET /api/projects/:slug/modules — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/modules"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/modules-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export bundle
  "GET /api/bundle — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/bundle"
   :rest/response slopp-server.ui.wire.contracts/bundle-response})

(def ^{:generated "source" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export source
  "GET /api/projects/:slug/source/:ns/:name — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/source/:ns/:name"
   :http/params   #{:name :ns :slug}
   :rest/request  slopp-server.ui.wire.contracts/source-request
   :rest/response slopp-server.ui.wire.contracts/source-response})

(def ^{:generated "search" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export search
  "GET /api/projects/:slug/search — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/search"
   :http/params   #{:limit :q :slug}
   :rest/request  slopp-server.ui.wire.contracts/search-request
   :rest/response slopp-server.ui.wire.contracts/search-response})

(def ^{:generated "module" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export module
  "GET /api/projects/:slug/module/:m — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/module/:m"
   :http/params   #{:m :slug}
   :rest/request  slopp-server.ui.wire.contracts/module-request
   :rest/response slopp-server.ui.wire.contracts/module-response})

(def ^{:generated "ns-outline" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export ns-outline
  "GET /api/projects/:slug/ns/:ns — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/ns/:ns"
   :http/params   #{:ns :slug}
   :rest/request  slopp-server.ui.wire.contracts/ns-outline-request
   :rest/response slopp-server.ui.wire.contracts/ns-outline-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export otel-endpoint
  "POST /api/otel/v1/logs — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/otel/v1/logs"
   :http/params   #{:resourceLogs}
   :rest/request  slopp-server.ui.wire.contracts/otel-endpoint-request
   :rest/response slopp-server.ui.wire.contracts/otel-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export status-endpoint
  "GET /api/status — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/status"
   :rest/response slopp-server.ui.wire.contracts/status-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export mcp-delete-endpoint
  "DELETE /api/projects/:slug/mcp — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :delete
   :http/path     "/api/projects/:slug/mcp"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/mcp-delete-endpoint-response})

(def ^{:generated "projects-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export projects-endpoint
  "GET /api/projects — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects"
   :rest/response slopp-server.ui.wire.contracts/projects-endpoint-response})

(def ^{:generated "hook-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export hook-endpoint
  "POST /api/hook — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/hook"
   :http/params   #{:hook}
   :rest/request  slopp-server.ui.wire.contracts/hook-endpoint-request
   :rest/response slopp-server.ui.wire.contracts/hook-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export mcp-post-endpoint
  "POST /api/projects/:slug/mcp — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/projects/:slug/mcp"
   :http/params   #{:error :id :jsonrpc :method :params :result :slug}
   :rest/request  slopp-server.ui.wire.contracts/mcp-post-endpoint-request
   :rest/response slopp-server.ui.wire.contracts/mcp-post-endpoint-response})

(def ^{:generated "cli-endpoint" :http/external-path "generated from the contract published at http://127.0.0.1:7358/api/projects/slopp/rest/paths"} ^:export cli-endpoint
  "POST /api/cli — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/cli"
   :rest/request  slopp-server.ui.wire.contracts/cli-endpoint-request
   :rest/response slopp-server.ui.wire.contracts/cli-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export mcp-get-endpoint
  "GET /api/projects/:slug/mcp — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :get
   :http/path     "/api/projects/:slug/mcp"
   :http/params   #{:slug}
   :rest/response slopp-server.ui.wire.contracts/mcp-get-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc" :unused-ok "a descriptor of the slopp server's surface this app does not call yet — kept so the hand-owned wire mirrors the whole published contract, as the generated one did"} ^:export call-endpoint
  "POST /api/projects/:slug/call — generated endpoint descriptor (D-web-contracts)."
  {:http/method   :post
   :http/path     "/api/projects/:slug/call"
   :http/params   #{:agent :arguments :slug :token :tool}
   :rest/request  slopp-server.ui.wire.contracts/call-endpoint-request
   :rest/response slopp-server.ui.wire.contracts/call-endpoint-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export story
  "GET /api/story/:grain/:subject — a namespace's or a module's history, told by commit point."
  {:http/method   :get
   :http/path     "/api/story/:grain/:subject"
   :http/params   #{:grain :subject :page}
   :rest/request  slopp-server.ui.wire.contracts/story-request
   :rest/response slopp-server.ui.wire.contracts/story-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export entries
  "GET /api/entries — every door into the store, by kind."
  {:http/method   :get
   :http/path     "/api/entries"
   :rest/response slopp-server.ui.wire.contracts/entries-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export form-sequence
  "GET /api/form/:id/sequence — what happens when one form runs, as the code writes it."
  {:http/method   :get
   :http/path     "/api/form/:id/sequence"
   :http/params   #{:id :depth :steps}
   :rest/request  slopp-server.ui.wire.contracts/sequence-request
   :rest/response slopp-server.ui.wire.contracts/sequence-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export flow
  "GET /api/flow — the call path between two forms, drawn as a sequence."
  {:http/method   :get
   :http/path     "/api/flow"
   :http/params   #{:from :to}
   :rest/request  slopp-server.ui.wire.contracts/flow-request
   :rest/response slopp-server.ui.wire.contracts/sequence-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export overlay
  "GET /api/overlay/:dial — what one dial tints the Code map by."
  {:http/method   :get
   :http/path     "/api/overlay/:dial"
   :http/params   #{:dial}
   :rest/request  slopp-server.ui.wire.contracts/overlay-request
   :rest/response slopp-server.ui.wire.contracts/overlay-response})

(def ^{:http/external-path "a route on the slopp server, published in its contract; hand-owned since 2026-09-23, see the ns doc"} ^:export data
  "GET /api/data — the data dictionary, and with ?key= one key's users."
  {:http/method   :get
   :http/path     "/api/data"
   :http/params   #{:q :bare :key :limit}
   :rest/request  slopp-server.ui.wire.contracts/data-request
   :rest/response slopp-server.ui.wire.contracts/data-response})
