(ns slopp.build
  "The native-binary build target (O4): pure generators for everything an
  explicit `build!` needs to compile a store-built project into a
  self-contained executable via GraalVM native-image.

  The generated launcher uses `gen-class` — legal here because the D3/D4
  dialect gates *authored store code*; build output is host-generated
  scaffolding, the same standing as slopp.kernel.rt's instrumentation machinery.
  The dialect is also what makes this target reliable: the bans on
  eval/read-string/gen-class/user-macros are exactly the closed-world
  assumptions native-image needs.

  Recipe per clj-easy/graal-docs current practice: AOT-compile with direct
  linking, put com.github.clj-easy/graal-build-time on the classpath (its
  Feature registers Clojure classes for build-time init), `--no-fallback`."
  (:require [clojure.string :as str]))

(defn ^:export ^{:foreign-keys "clj-kondo's var-definition map — its spelling is not ours to change"
        :malli/schema [:=> {:throws []} [:cat [:map
                                  [:fixed-arities {:optional true} [:maybe [:set :int]]]
                                  [:varargs-min-arity {:optional true} [:maybe :int]]]]
                       [:enum :vector :apply]]}
  arg-style
  "How the launcher hands CLI args to the entry fn, judged from its index
  var-definition: a single fixed arity of 1 (and no varargs) receives the
  args as ONE vector; every other shape is `apply`'d, -main style.

  The arg is clj-kondo's var-definition map, hence `^:foreign-keys` — its
  spelling is not ours to change. The `:=>` schema is generatively checked
  (this fn is referentially transparent), so it states the real shape."
  [{:keys [fixed-arities varargs-min-arity]}]
  (if (and (nil? varargs-min-arity) (= #{1} (set fixed-arities)))
    :vector
    :apply))

(defn ^:export launcher-source
  "The generated `src/native/main.clj`: a gen-class entry delegating to
  `main-sym`, exiting cleanly (flush + shutdown-agents, so a lingering agent
  thread pool can't hang the binary)."
  [main-sym style]
  (str "(ns native.main\n"
       "  \"Generated by slopp build! — do not edit; rebuild instead.\"\n"
       "  (:require [" (namespace main-sym) "])\n"
       "  (:gen-class))\n"
       "\n"
       "(defn -main [& args]\n"
       (case style
         :vector (str "  (" main-sym " (vec args))\n")
         :apply  (str "  (apply " main-sym " args)\n"))
       "  (flush)\n"
       "  (shutdown-agents))\n"))

(defn- coerce-exclusions
  "tools.deps requires a coord's `:exclusions` to be SYMBOLS; an MCP-supplied
  coord carries them as strings (JSON has no symbol type). Coerce each so the
  projected deps.edn resolves — a string exclusion makes make_classpath2 fail
  in every fresh JVM (build, external test tier, native), while the live
  hot-add tolerates it."
  [deps]
  (into {}
        (map (fn [[lib coord]]
               [lib (cond-> coord
                      (:exclusions coord)
                      (update :exclusions
                              (fn [xs] (mapv #(if (string? %) (symbol %) %) xs))))]))
        deps))

(defn ^:export client-compiler
  "The configured client-side compiler for `store` (D-web-cljs) — read from the
  `client` config file's `compiler` key, defaulting to :clojurescript. The
  compile step DISPATCHES on this, so cherry/squint can be plugged in per
  project (`config_file {path \"client\" key \"compiler\" value \"cherry\"}`)
  without re-authoring a single stored form — the `.cljs`/`.cljc` source is
  compiler-agnostic. Only :clojurescript is implemented today."
  [store]
  (keyword (or (get-in store [:config "client" :values "compiler"])
               "clojurescript")))

^:unsafe (defn ^:export deps-edn
  "deps.edn for the built project; `deps` (lib→coord, the store's Tier-1
  manifest) becomes the `:deps` map so a built project is runnable; with
  `native?`, adds the :native alias (AOT output path, graal-build-time, direct
  linking) — manifest deps flow to the native classpath via `-Spath -A:native`;
  with `test?`, adds a `:test` alias putting `test/` on an extra-path AND
  carrying the cognitect test-runner, so `clojure -M:test` runs the project's
  suite out of the box (the external runner builds+runs exactly this).

  With `trace?`, BOTH test aliases enter through `slopp.image.testmain` — the trace
  runner that WRAPS cognitect — so the external tier yields a form trace
  (#121, the only tier that runs ^:external tests). Cognitect stays in
  :extra-deps: the runner resolves it there and delegates, leaving the output
  the summary parsers read untouched. Both aliases and not one, because `done`
  runs :test-run narrowed while `commit_point` runs :test full — tracing only
  one entry leaves a hole exactly where the gate is.

  With `client-deps` (the BUILD-ONLY cljs compiler manifest, D-web-cljs), adds a
  `:cljs` alias carrying those deps + the `cljs-src` extra-path, so
  `clojure -A:cljs` resolves the ClojureScript compiler for the compile step —
  and they NEVER enter the runtime `:deps` that ships. Absent client-deps the
  alias is omitted, so output is unchanged.

  With `instruments?` (the store declares a module `:instrument`, R5), adds
  `instruments` to `:paths` — a RUN path, not an alias, because an instrument
  is code a human runs. What keeps it OUT of the jar is that our build script
  copies `src` by name: the exclusion needs no build script that knows what a
  role is, which is the same property that makes `test/` a separate root
  rather than a marker inside `src/`.

  With an EMPTY manifest and no test/native/cljs aliases and no instruments the
  output is byte-identical to the pre-manifest version (the build! `ours?`
  byte-identity guard relies on this)."
  ([native?] (deps-edn native? {}))
  ([native? deps] (deps-edn native? deps false))
  ([native? deps test?] (deps-edn native? deps test? false))
  ([native? deps test? trace?] (deps-edn native? deps test? trace? {}))
  ([native? deps test? trace? client-deps]
   (deps-edn native? deps test? trace? client-deps false))
  ([native? deps test? trace? client-deps instruments?]
   ;; bind *print-namespace-maps* OFF: it defaults true at a REPL, false in a
   ;; script — leaving it would make output non-deterministic (the git
   ;; projection + build! ours? guard both depend on byte-stable output).
   (let [deps-str (if (seq deps)
                    (str " :deps " (binding [*print-namespace-maps* false]
                                     (pr-str (coerce-exclusions deps))))
                    "")
         paths    (if instruments? "[\"src\" \"instruments\"]" "[\"src\"]")
         main-ns  (if trace? "slopp.image.testmain" "cognitect.test-runner")
         ;; each alias entry is "KEY\n  {VALUE}"; the first sits right after the
         ;; aliases-map `{` (matching the historical single-:native layout), the
         ;; rest are 2-space-indented — order is deterministic (test, native, cljs).
         aliases  (cond-> []
                    test?   (conj (str ":test\n"
                                       "  {:extra-paths [\"test\"]\n"
                                       "   :extra-deps  {io.github.cognitect-labs/test-runner\n"
                                       "                 {:git/tag \"v0.5.1\" :git/sha \"dfb30dd\"}}\n"
                                       "   :main-opts   [\"-m\" \"" main-ns "\"\n"
                                       "                 \"-d\" \"test\" \"-d\" \"src\" \"-r\" \".*\"]}")
                                  ;; :test-run = same runner WITHOUT the baked -r
                                  ;; regex: -n/-v args actually narrow (the baked
                                  ;; -r unions with -n in cognitect's runner)
                                  (str ":test-run\n"
                                       "  {:extra-paths [\"test\"]\n"
                                       "   :extra-deps  {io.github.cognitect-labs/test-runner\n"
                                       "                 {:git/tag \"v0.5.1\" :git/sha \"dfb30dd\"}}\n"
                                       "   :main-opts   [\"-m\" \"" main-ns "\"\n"
                                       "                 \"-d\" \"test\" \"-d\" \"src\"]}"))
                    native? (conj (str ":native\n"
                                       "  {:extra-paths [\"classes\"]\n"
                                       "   :extra-deps  {com.github.clj-easy/graal-build-time {:mvn/version \"1.0.5\"}}\n"
                                       "   :jvm-opts    [\"-Dclojure.compiler.direct-linking=true\"]}"))
                    (seq client-deps)
                    (conj (str ":cljs\n"
                               "  {:extra-paths [\"cljs-src\"]\n"
                               "   :extra-deps  "
                               (binding [*print-namespace-maps* false]
                                 (pr-str (coerce-exclusions client-deps)))
                               "}")))]
     (if (empty? aliases)
       (str "{:paths " paths deps-str "}\n")
       (str "{:paths " paths deps-str "\n"
            " :aliases\n"
            " {" (str/join "\n  " aliases) "}}\n")))))

(defn ^:export cli-launcher-source
  "The generated `src/native/main.clj` for a COMMAND-LINE app: a gen-class entry
  that scans `command-nses` for commands and runs one invocation of them under
  the program name `prog`.

  The counterpart of [[launcher-source]], and the difference between them is the
  point of the `cli` capability. That one delegates to an entry fn the AUTHOR
  wrote, so it has to inspect the fn's arity to decide how to hand over argv —
  and everything after that (parsing, streams, usage, status codes) is the
  author's problem, re-solved per app and wrong in a different way each time.
  This one delegates to slopp's own `run`, whose shape is known, so there is no
  arity to inspect and none of that is the author's problem.

  **The command namespaces are REQUIRED, not merely passed.** `commands-in`
  discovers commands with `find-ns`, and a namespace that is not loaded
  contributes nothing rather than throwing — the deliberate choice that lets a
  partially-loaded image still answer. In a compiled binary that same leniency
  turns a missing require into a program with no commands and no error: a bare
  invocation prints an empty list, and every real one says \"unknown command\".
  So the require clause and the scan list are generated from ONE argument.

  **`System/exit` lives here and nowhere else.** `run` returns `{:cli/exit …}`
  rather than exiting, so a test and a process see the same value and only the
  process acts on it. `flush` precedes it because stdout is buffered and
  `System/exit` does not drain it — a command that printed its answer and
  exited non-zero would otherwise lose the answer. `shutdown-agents` is
  deliberately absent, unlike [[launcher-source]]: it is there to stop a
  lingering agent pool from hanging a binary that RETURNS from -main, and a
  process that exits explicitly cannot hang that way."
  [prog command-nses]
  (let [nses (vec command-nses)]
    (str "(ns native.main\n"
         "  \"Generated by slopp build! — do not edit; rebuild instead.\"\n"
         "  (:require "
         (str/join "\n            "
                   (cons "[slopp.cli]" (for [n nses] (str "[" n "]"))))
         ")\n"
         "  (:gen-class))\n"
         "\n"
         "(defn -main [& args]\n"
         "  (let [result (slopp.cli/run\n"
         "                (slopp.cli/context\n"
         "                 {:cli/name \"" prog "\"\n"
         "                  :cli/commands (slopp.cli/commands-in '" (pr-str nses) ")})\n"
         "                args)]\n"
         "    (flush)\n"
         "    (System/exit (:cli/exit result))))\n")))

(defn ^:export native-script
  "build-native.sh: AOT-compile the launcher (and, transitively, the app),
  then native-image the result into `bin-name`. `asset-paths` (the file
  manifest's paths) copy into classes/ — putting them on the compile
  classpath as resources — and ride -H:IncludeResources, so the binary
  serves its own assets."
  [bin-name asset-paths]
  (let [assets (vec (sort (map str asset-paths)))
        copies (apply str
                      (for [p assets]
                        (let [dir (let [i (.lastIndexOf ^String p "/")]
                                    (when (pos? i) (subs p 0 i)))]
                          (str (when dir (str "mkdir -p \"classes/" dir "\"\n"))
                               "cp \"" p "\" \"classes/" p "\"\n"))))
        include (when (seq assets)
                  (str "  -H:IncludeResources='"
                       (clojure.string/join "|"
                                            (map #(clojure.string/replace % "." "\\.")
                                                 assets))
                       "' \\\n"))]
    (str "#!/usr/bin/env bash\n"
         "# Generated by slopp build! — compiles this project to a native binary.\n"
         "# Needs GraalVM 21+ on PATH (native-image ships inside the JDK; no gu).\n"
         "set -euo pipefail\n"
         "cd \"$(dirname \"$0\")\"\n"
         "\n"
         "command -v native-image >/dev/null 2>&1 || {\n"
         "  echo \"native-image not found — install GraalVM 21+ (e.g.\" >&2\n"
         "  echo \"mise install java@graalvm-community-21, or graalvm.org)\" >&2\n"
         "  exit 1\n"
         "}\n"
         "\n"
         "mkdir -p classes\n"
         copies
         "clojure -M:native -e \"(compile 'native.main)\"\n"
         "\n"
         "native-image \\\n"
         "  -cp \"classes:$(clojure -Spath -A:native)\" \\\n"
         "  -o \"" bin-name "\" \\\n"
         "  --no-fallback \\\n"
         include
         "  --features=clj_easy.graal_build_time.InitClojureClasses \\\n"
         "  native.main\n"
         "\n"
         "echo \"built ./" bin-name "\"\n")))

(defn ^:export compiler-coord
  "The build-only dependency coordinate [lib coord] for a client-compiler
   keyword (the compiler slopp DISPATCHES to), or nil for a backend slopp has
   no bundled default for. Only :clojurescript is implemented today; cherry /
   squint would add rows here when their backends land."
  [compiler]
  (case compiler
    :clojurescript ['org.clojure/clojurescript {:mvn/version "1.11.132"}]
    nil))

(defn ^:export webapp-launcher-source
  "The generated `src/native/client.cljs` for a BROWSER app: require the
  namespaces the page reaches, mount it, and start when the document is ready.

  The counterpart of [[cli-launcher-source]], and the difference between them is
  what `webapp` is for. A cli app's alternative to a generated launcher is a
  `-main` the author writes once. A browser app's alternative is TWO wirings —
  the `:cljs` shell that mounts and whatever the headless driver is handed — and
  a hand-written adapter between them, which is what the only real webapp built
  on slopp had. Nothing compared the three.

  **Deliberately THIN: require, mount, bootstrap.** Everything browser-shaped —
  the render loop, click delegation, popstate, reading the mount point — is in
  `slopp.webapp.dom/mount!`, the one `:cljs` namespace slopp ships. A fat
  generated entry would be a second home for browser logic in a namespace whose
  only verification is that it compiled, which is the condition this capability
  exists to end rather than to relocate. `slopp.webapp.dom` earns that place by
  being unable to branch, which is checked; a generated string could not be.

  **The page namespaces are REQUIRED, not merely named.** Same failure as the
  cli launcher one process out, with a worse symptom: there, an unrequired
  namespace produced a program with no commands; here it is a call to a var that
  does not exist, which reaches a reader as a blank page and reads like a
  rendering bug rather than a wiring one.

  **The bootstrap is a top-level `defonce`, and that is a SECURITY property.**
  `compile_client` emits a bundle whose top-level forms run when the `<script>`
  loads, so the document starts the app with no inline JS and the page stays
  script-src-only. An inline starter would put `unsafe-inline` into the CSP of
  every app built on this capability — raised by slopp-ui before it was decided,
  in a programme whose stated motivation is that an agent should not be able to
  build something insecure by accident. `defonce` guards a double mount if the
  bundle is ever evaluated twice.

  The readyState branch is not ceremony: a bundle loaded from `<head>` runs
  before the mount point exists, and mounting into nothing is a blank page with
  no error."
  [page-sym page-nses]
  (let [nses (vec page-nses)]
    (str "(ns native.client\n"
         "  \"Generated by slopp build! — do not edit; rebuild instead.\"\n"
         "  (:require [slopp.webapp.dom :as dom]\n"
         (str/join "\n" (for [n nses] (str "            [" n "]")))
         "))\n"
         "\n"
         "(defn ^:export main []\n"
         "  (dom/mount! (" page-sym ")))\n"
         "\n"
         "(defonce ^{:unused-ok \"nothing CALLS it — the BUNDLE runs it. A top-level"
         " form is what lets the document start the app with no inline JS, so the"
         " page stays script-src-only; a caller would mean markup carrying script\"}\n"
         "  bootstrap\n"
         "  (if (= \"loading\" js/document.readyState)\n"
         "    (js/document.addEventListener \"DOMContentLoaded\" (fn [_] (main)))\n"
         "    (main)))\n")))
